version: '3.7'

services:
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx-proxy
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./ssl/certs:/etc/nginx/certs
  #   ports:
  #     - "443:443"
  #     - "80:80"
  #   depends_on:
  #     - bank-app
  #     - wall-app
  #   networks:
  #     - nginx-proxy-net

  traefik:
    image: "traefik:v3.0"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      - "8082:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  bank:
    image: bank-app
    container_name: bank
    build:
      context: ./bank_app/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bank.rule=Host(`bank.powerzio.net`)"
      - "traefik.http.routers.bank.entrypoints=web"
    volumes:
      - ./bank_app/app:/usr/app

  wall:
    image: wall
    container_name: wall
    build:
      context: ./wall_app/wall
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wall.rule=Host(`wall.powerzio.net`)"
      - "traefik.http.routers.wall.entrypoints=web"
    volumes:
      - ./wall_app/wall:/usr/app

  dns:
    image: andyshinn/dnsmasq
    container_name: dns
    ports:
      - "53:53"
    volumes:
      - ./dns/dnsmasq.conf:/etc/dnsmasq.conf
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      - nginx-proxy-net

networks:
  nginx-proxy-net:
    driver: bridge

  # prometheus:
  #   image: prom/prometheus
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"

  # grafana:
  #   image: grafana/grafana
  #   ports:
  #     - "3000:3000"

  # alertmanager:
  #   image: prom/alertmanager
  #   volumes:
  #     - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
  #   ports:
  #     - "9093:9093"
