version: '3.7'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/sites-enabled/nginx.conf
    ports:
      - "9001:9001"
    depends_on:
      - bank-app
      - wall-app
    networks:
      - app-network

  bank-app:
    build:
      context: ./bank_app/app
    ports:
      - "8080:5000"
    volumes:
      - ./bank_app/app:/usr/app
    networks:
      - app-network

  wall-app:
    container_name: wall-app
    build:
      context: ./wall_app/wall
    ports:
      - "8081:80"
    volumes:
      - ./wall_app/wall:/usr/app
    networks:
      - app-network
  dns:
    image: andyshinn/dnsmasq
    container_name: dns
    ports:
      - "53:53"
    volumes:
      - ./dns/dnsmasq.conf:/etc/dnsmasq.conf
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      - app-network


networks:
  app-network:
    driver: bridge





  # prometheus:
  #   image: prom/prometheus
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"

  # grafana:
  #   image: grafana/grafana
  #   ports:
  #     - "3000:3000"

  # alertmanager:
  #   image: prom/alertmanager
  #   volumes:
  #     - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
  #   ports:
  #     - "9093:9093"
